### ISSUE TITLE
text.replace is not a function

### ISSUE THREAD

**Issue by nstjames** [seb303/DnBrowse#1]
I tried out DN browser but it seems to have issues loading a map data with list of maps in my server.
Apparently the map data became an JSON which it yeah cannot use string function replace
![image](https://user-images.githubusercontent.com/67573495/183793843-8b74a23d-69d0-474a-98f7-0d8017c8ea0f.png)

**Comment by nstjames** [comment]
as sample data, here is what my server contains:

`map@[dnbrowse_active=map@[__value=true];event=map@[__value=map@[consume=map@[__value=map@[token_of_forgiveness=map@[__value=map@[success=map@[__value=map@[3524140a-a971-4178-a60e-6852021c4de3=map@[__value=li@map@[uuid=3524140a-a971-4178-a60e-6852021c4de3;createdOn=time@2022/08/09_17:55:24:0800_+08:00;owner=Servlet;consumedOn=time@2022/08/09_17:57:49:0470_+08:00]|];7c3f97c9-c8ee-4b9a-9d72-cd5b819cb010=map@[__value=li@map@[uuid=7c3f97c9-c8ee-4b9a-9d72-cd5b819cb010;createdOn=time@2022/08/09_17:58:43:0250_+08:00;owner=Servlet;consumedOn=time@2022/08/09_18:01:39:0549_+08:00]|];90e89051-e349-41e5-aeee-f999fe276d76=map@[__value=li@map@[uuid=90e89051-e349-41e5-aeee-f999fe276d76;createdOn=time@2022/08/09_18:04:16:0700_+08:00;owner=Servlet;consumedOn=time@2022/08/09_18:05:10:0401_+08:00]|];8efe769e-81ac-4446-8a47-88f4a1565405=map@[__value=li@map@[uuid=8efe769e-81ac-4446-8a47-88f4a1565405;createdOn=time@2022/08/09_18:05:40:0350_+08:00;owner=Servlet;consumedOn=time@2022/08/09_18:05:48:0700_+08:00]|];4e0c2faa-b555-4114-8cad-5f70e81de8c0=map@[__value=li@map@[uuid=4e0c2faa-b555-4114-8cad-5f70e81de8c0;createdOn=time@2022/08/09_18:53:35:0757_+08:00;owner=Leo;consumedOn=time@2022/08/09_19:16:54:0881_+08:00]|];cf75a789-ecfd-4de9-86bc-95c24b84bc7c=map@[__value=li@map@[uuid=cf75a789-ecfd-4de9-86bc-95c24b84bc7c;createdOn=time@2022/08/09_19:17:02:0708_+08:00;owner=Leo;consumedOn=time@2022/08/09_19:21:36:0417_+08:00]|];86a77129-3b77-42ca-9d77-220628a0fbff=map@[__value=li@map@[uuid=86a77129-3b77-42ca-9d77-220628a0fbff;createdOn=time@2022/08/09_19:22:28:0058_+08:00;owner=player.name;consumedOn=time@2022/08/09_19:22:44:0463_+08:00]|];c7ed36a7-6802-488c-a704-0a3983d11d62=map@[__value=li@map@[uuid=c7ed36a7-6802-488c-a704-0a3983d11d62;createdOn=time@2022/08/09_19:23:16:0957_+08:00;owner=player.name;consumedOn=time@2022/08/09_19:23:21:0314_+08:00]|]]]]]]]]];dnbrowse_secret=map@[__value=map@[6ne3ub2fvrmj=map@[__value=p@3128f177-566e-4b70-87f4-d81bfb75c2e7;__expiration=time@2022/08/10_10:16:42:0813_+08:00]]]]`

**Comment by seb303** [comment]
Should be fixed now.  Please download a new copy of dnbrowse.js and try it.
Also a minor change to dnbrowse.dsc (not related to this bug)

**Comment by nstjames** [comment]
> 

Kudos! that works flawlessly.
