### ISSUE TITLE
List of Items turns into [Object object]

### ISSUE THREAD

**Issue by nstjames** [seb303/DnBrowse#2]
Seems like the parser for the Player Flags part of the webapp didn't process the object for rendering.

![image](https://user-images.githubusercontent.com/67573495/183833086-5a5f1906-1853-4069-815f-9a33a9c2970e.png)

Here is the data from my player. I was using head database denizen script so it contains that.

https://pastebin.com/Jr7ZDaXY

**Comment by seb303** [comment]
Woops, that's a bug introduced by the last fix.  Should be fixed now.

**Comment by nstjames** [comment]
> Woops, that's a bug introduced by the last fix. Should be fixed now.

Works great now! Thanks for the rapid fix!
